version: '3.7'

services:
  web:
    container_name: mprj-django
    build: ./app
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000 --noreload"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "${DJANGO_PORT:-80}:8000"
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - frontend
      - backend
  database:
    image: postgres:12.0-alpine
    container_name: mprj-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${SQL_USER:-postgres}
      POSTGRES_PASSWORD: ${SQL_PASSWORD:-123456}
      POSTGRES_DB: ${SQL_DATABASE:-mprj}
    networks:
      - backend
  pgadmin:
    image: dpage/pgadmin4
    container_name: mprj-pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-123456}
    ports:
      - "${PGADMIN_PORT:-8081}:80"
    networks:
      - frontend
      - backend
  redis:
    image: redis
    container_name: mprj-redis
    command: redis-server
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - backend
networks:
  frontend:
  backend:
volumes:
  postgres_data: