# Generated by Django 3.1 on 2021-07-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('id_doc', models.IntegerField()),
                ('id_tjrj', models.IntegerField()),
                ('hash_tramitacao', models.CharField(max_length=32)),
            ],
        ),
    ]
